export const ALL_PRODUCT_REQUEST="ALL_PRODUCT_REQUEST"
export const ALL_PRODUCT_SUCCESS="ALL_PRODUCT_SUCCESS"
export const ALL_PRODUCT_FAIL="ALL_PRODUCT_FAIL"

export const PRODUCT_DETAIES_REQUEST="PRODUCT_DETAIES_REQUEST"
export const PRODUCT_DETAIES_SUCCESS="PRODUCT_DETAIES_SUCCESS"
export const PRODUCT_DETAIES_FAIL="PRODUCT_DETAIES_FAIL"

export const CLEAR_ERRORS="CLEAR_ERRORS"

