export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"

export const REGISTER_USER_REQUEST="REGISER_USER_REQUEST"
export const REGISTER_USER_SUCCESS="REGISER_USER_SUCCESS"
export const REGISTER_USER_FAIL="REGISER_USER_FAIL"

export const CLEAR_ERRORS="CLEAR_ERRORS"
