export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"

export const REGISTER_USER_REQUEST="REGISER_USER_REQUEST"
export const REGISTER_USER_SUCCESS="REGISER_USER_SUCCESS"
export const REGISTER_USER_FAIL="REGISER_USER_FAIL"

export const LOAD_USER_REQUEST="LOAD_USER__REQUEST"
export const LOAD_USER_SUCCESS="LOAD_USER__SUCCESS"
export const LOAD_USER_FAIL="LOAD_USER__FAIL"

export const LOGOUT_SUCCESS="LOGOUT__SUCCESS"
export const LOGOUT_FAIL="LOGOUT__FAIL"

export const UPDATE_PROFILE_REQUEST="UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS="UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_RESET="UPDATE_PROFILE_RESET"
export const UPDATE_PROFILE_FAIL="UPDATE_PROFILE_FAIL"

export const CLEAR_ERRORS="CLEAR_ERRORS"
